'use client';

const TestLockersArray = [
    {question : "¿Qué medidas de Lockers se ofrecen?" , answer: "Ofrecemos diferentes medidas en función de tus necesidades. Puedes consultarlas en esta misma página, un poco más arriba."},
    {question : "¿Cómo puedo reservar mi Locker?" , answer: "Las reservas se pueden hacer por adelantado y son válidas desde el mismo momento en que la realizas. También se puede hacer en el mismo festival."},
    {question : "¿Qué puedo introducir dentro de mi Locker?" , answer: "Puedes introducir todos los bultos que entren dentro del Locker alquilado, con excepción de los artículos prohibidos. Recuerda que pagas por Locker alquilado, no por bulto, por lo que puedes introducir todos los bultos que entren en tu Locker."},
    {question : "¿Qué está prohibido almacenar dentro de mi Locker?" , answer: "Todos los objetos cuya mera tenencia o tráfico sea ilegal (tales como, objetos robados, drogas, materiales pornográficos o, de cualquier modo, denigrantes para el ser humano, etc.). Objetos cuya tenencia requiera de licencia, sin dicha licencia o autorización (como por ejemplo, armas y/o munición). Todo tipo de material que sea contaminante o sea peligroso (tales como, objetos inflamables o substancias peligrosas). Animales de cualquier tipo o cualquier otro tipo de ser vivo. No se puede insertar en las Lockers comida, salvo que se trate de comida envasada que no pueda derramarse, manchar las Lockers o producir olores de ningún tipo."},
    {question : "¿Está mi equipaje asegurado?" , answer: "Mobile Locker y Aquasella no se hacen responsables de los objetos depositados en el interior de los lockers."},
    {question : "¿Durante cuánto tiempo puedo alquilar un Locker?" , answer: "Podrás contratar el servicio de alquiler de Lockers por un período de entre 1 día (disponible solo en el mismo festival) y lo que dure el festival (disponible ya online)."},
    {question : "¿Cuándo puedo acceder al Locker que he alquilado?" , answer: "El servicio de alquiler de cada Locker estará accesible en el horario del festival."},
    {question : "¿Qué ocurre si no recojo mis objetos durante el periodo contratado?" , answer: "Tu objetos estarán dentro del mismo locker y deberás pagar el coste del tiempo extra. En caso de que el evento finalizara tus objetos se entregarán a objetos perdidos del festival."},
    {question : "¿Se puede cargar dispositivos móviles en los lockers?" , answer: "Cada locker dispone de un enchufe para poder conectar y hacer la carga de un dispositivo móvil. No incluye el cable. En los lockers de ubicaciones públicas no existe la opción de carga de móviles."},
    {question : "¿Una vez insertados los bultos puedo volver a acceder a la Locker?" , answer: "Puedes acceder al Locker alquilado tantas veces como desees o lo necesites durante el período de alquiler del Locker. Por lo tanto, si has olvidado algo, quieres añadir más bultos o necesitas acceder a tu Locker durante el periodo alquilado, lo podrás hacer sin problemas."},
    {question : "¿Cómo se utilizan las Lockers?" , answer: "Puedes acceder al Locker alquilado tantas veces como desees o lo necesites durante el período de alquiler del Locker. Por lo tanto, si has olvidado algo, quieres añadir más bultos o necesitas acceder a tu Locker durante el periodo alquilado, lo podrás hacer sin problemas."},
    {question : "¿Qué puedo hacer si tengo una incidencia en el uso de la Locker?" , answer: "Puedes acceder al Locker alquilado tantas veces como desees o lo necesites durante el período de alquiler del Locker. Por lo tanto, si has olvidado algo, quieres añadir más bultos o necesitas acceder a tu Locker durante el periodo alquilado, lo podrás hacer sin problemas."},
]

export default TestLockersArray