import { inter, roboto_mono, bebas_neue } from "./fonts.js";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Video from "@/components/Video/Video";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bebas_neue.className}>
        <NavBar/>
        
        {children}
        </body>
      
    </html>
  );
}
